subjects = ['Classical Mechanics', 'Statistical Mechanics', 'Relativistic Mechanics', 'Fluid Mechanics']
print(len(subjects))
subjects.append('Qed')
print(subjects)
subjects.insert(2, 'Qgd')
print(subjects)
subjects.remove('Statistical Mechanics')
print(subjects)
subjects.sort()
print(subjects)
subjects.reverse()
print(subjects)
subjects.pop()
print(subjects)
subjects2 = subjects.copy()
print(subjects2)
pos = subjects.index('Qed')
print(pos)
count = subjects.count('Qed')
print(count)